common: &common
  adapter:  postgresql
  username: postgres
  encoding: unicode
  pool:     5

development:
  <<: *common
  database: board_development

test:
  <<: *common
  database: board_test

production:
  <<: *common
  database: board_production
