common: &common
  adapter:  postgresql
  host:     localhost
  port:     5433
  username: rails
  password: rails
  encoding: unicode
  pool:     5

development:
  <<: *common
  database: board_development

test:
  <<: *common
  database: board_test

production:
  <<: *common
  database: board_production
